### ISSUE TITLE
Original text preservation

### ISSUE THREAD

**Issue by capdevc** [emorynlp/tokenization#1]
re: clir/clearnlp#9
Dr. Choi,

I'm using ClearNLP at the moment, but needed to be able to preserve/mark up the original text. The easiest way to do this for me was to use another tokenizer that generated begin/end offsets for each token and then to subclass DEPNode to include that info. I then had a list of DEPNodes and generated the DEPTree from those and passed that into the rest of the ClearNLP pipeline.

There's been interest in adding something like that here, and I think I could contribute code to make it work, but the problem is that the current tokenizer just returns a sequence of strings and I'm not sure how you would want this extra info added. Are you going to be using the same DEPTree/DEPNode data structures from Clear? Should this tokenizer go ahead and return a DEPTree? A seq of DEPNodes? A seq of tuples containing the tokens and offset info? Some entirely new Token type? Optionally do 2 or more of those things?

I'm happy to take a crack at it and submit a PR but I want to make sure I do it in a way that fits your future plans.

**Comment by jdchoi77** [comment]
Sorry, I completely missed this issue:)  This feature is now integrated in our tokenizer; NLPNode has two fields, start_offset and end_offset, that keeps the indices from the original text.  I'll release emorynlp next week so please let me know if this helps.  Thanks.

best,

Jinho
